services:
  # Service 1: Your Java application (built from Dockerfile)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitchensink
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/kitchensink?authSource=admin
    depends_on:
      - mongodb  # Ensures MongoDB is started before the app

  # Service 2: MongoDB (official MongoDB image)
  mongodb:
    image: mongo:6.0.20-rc3  # Use the official MongoDB image (version 6.0 or the latest)
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"  # Map MongoDB port to the host
    volumes:
      - mongo-data:/data/db  # Persistent data storage for MongoDB

volumes:
  mongo-data:
    driver: local
