spring:
  application:
    name: kitchensink
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME:mongoadmin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:secret}
      database: ${SPRING_DATA_MONGODB_DATABASE:kitchensink}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
